AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - db/migrate/**/*
    - vendor/**/*
    - bin/*
    - config/**/*
    - Gemfile
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - Rakefile
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4

Layout/CaseIndentation:
  Enabled: false

Layout/DefEndAlignment:
  AutoCorrect: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1,2]

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/IndentationConsistency:
  # prescribes that in classes and modules the `protected` and `private`
  # modifier keywords shall be indented the same as public methods and that
  # protected and private members shall be indented one step more than the
  # modifiers.
  EnforcedStyle: indented_internal_methods

Layout/IndentationWidth:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  AutoCorrect: true
  EnforcedStyle: indented

Layout/Tab:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/BracesAroundHashParameters:
  AutoCorrect: true

Style/ColonMethodCall:
  AutoCorrect: true

Style/ConditionalAssignment:
  Enabled: false

Style/ExpandPathArguments:
  AutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  AutoCorrect: true

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodDefParentheses:
  AutoCorrect: true

Style/ModuleFunction:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantParentheses:
  AutoCorrect: true

Style/RedundantException:
  AutoCorrect: true

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  AutoCorrect: true

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  AutoCorrect: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  AutoCorrect: true
  EnforcedStyleForMultiline: comma

Style/UnneededInterpolation:
  AutoCorrect: true

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false